GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2MzhhODVlMWI5ZGJjNDFhYWRhNzBkZTQiLCJpYXQiOjE2NzAzMDI1OTMsImV4cCI6MTY3MDMwNjE5M30.OxBKYsK1wuk9EGq7vOY-GdM8KVTM3gH-ccUKPpnkshU