POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzhiYjBhNWQyZjZkNGQ1MjhjZDQwNzkiLCJpYXQiOjE2NzcwODkyOTcsImV4cCI6MTY3NzA5Mjg5N30.JQGBj0KgtLiajdiX84shIjFYkDpD0M-jLM1H6d01kJgeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzhiYjBhNWQyZjZkNGQ1MjhjZDQwNzkiLCJpYXQiOjE2NzcwODkyOTcsImV4cCI6MTY3NzA5Mjg5N30.JQGBj0KgtLiajdiX84shIjFYkDpD0M-jLM1H6d01kJg

{
  "title": "9to5Mac22333",
  "author": "Dieter Brown",
  "url": "9to5mac.com",
  "likes": "3"
}